In [2]:
import pandas as pd  
import numpy as np  
from numpy import linalg
from __future__ import division
from scipy import spatial

In [3]:
import os.path
import glob
os.getcwd()

'/home/nykabhishek/Documents/DTICryptotanshinone-master/PYTHON'

In [15]:
f = os.getcwd()+ '/mat_*.txt'
files = glob.glob(f)

for filename in files:
    M = np.loadtxt(filename)
    Sim = 1 - spatial.distance.pdist(M, 'jaccard')
    Sim = spatial.distance.squareform(Sim)
    Sim = Sim + np.eye(M.shape[0])
    np.nan_to_num(Sim)
    print(Sim)
    newfile = os.getcwd() +  '/Sim_mat_' + filename[66:76] + '.txt'
    print(newfile)
    np.savetxt(newfile,Sim)

[[ 1. nan  0. ...  0.  0.  0.]
 [nan  1.  0. ...  0.  0.  0.]
 [ 0.  0.  1. ...  0.  0.  0.]
 ...
 [ 0.  0.  0. ...  1.  0.  0.]
 [ 0.  0.  0. ...  0.  1.  0.]
 [ 0.  0.  0. ...  0.  0.  1.]]
/home/nykabhishek/Documents/DTICryptotanshinone-master/PYTHON/Sim_mat_drug_drug..txt
[[ 1.  0.  0. ...  0.  0.  0.]
 [ 0.  1.  0. ... nan  0.  0.]
 [ 0.  0.  1. ...  0.  0.  0.]
 ...
 [ 0. nan  0. ...  1.  0.  0.]
 [ 0.  0.  0. ...  0.  1.  0.]
 [ 0.  0.  0. ...  0.  0.  1.]]
/home/nykabhishek/Documents/DTICryptotanshinone-master/PYTHON/Sim_mat_drug_prote.txt
[[1. 0. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 0. 1.]]
/home/nykabhishek/Documents/DTICryptotanshinone-master/PYTHON/Sim_mat_protein_pr.txt
[[ 1. nan  0. ... nan nan  0.]
 [nan  1.  0. ... nan nan  0.]
 [ 0.  0.  1. ...  0.  0.  0.]
 ...
 [nan nan  0. ...  1. nan  0.]
 [nan nan  0. ... nan  1.  0.]
 [ 0.  0.  0. ...  0.  0.  1.]]
/home/nykabhi